# Generated by Django 4.1.6 on 2023-02-05 07:32

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Robert Regalado", email="rojre@gmail.com", document="22342342", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
